[build]
  command = "next build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "next"
  command = "next dev"
  port = 3000
